apiVersion: v1
kind: Service
metadata:
  name: demo-fe-service-prod
  namespace: demo-prod-ns
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 80
  selector:
    app: demo-fe-dep-prod
