apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-fe-dep
spec:
  selector:
    matchLabels:
      app: demo-fe-dep
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-fe-dep
        track: stable
    spec:
      containers:
        - name: demo-fe-dep
          image: "gcr.io/ml-console-dev/demo-fe-image:latest"
          # resources:
          #   requests:
          #     memory: "1000Mi"
          #     cpu: "150m"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 80
          ports:
            - name: demo-fe-port
              containerPort: 80
